app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
   path('user_login/', views.user_login, name='user_login'),
   path('registration/', views.registration, name='registration'),
   path('logout/', views.user_logout, name='logout'),
   path('special/', views.special, name='special'),
]

regrevision/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index, name='index'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ProfileUserInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    portfoliowebsite = models.URLField(blank=True)
    photo = models.ImageField(upload_to='uploaded_pics/', blank=True)

    def __str__(self):
        return self.user.username

app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import ProfileUserInfoModel

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','email', 'password')


class ProfileUserInfoForm(forms.ModelForm):
    class Meta():
        model = ProfileUserInfoModel
        fields = ('portfoliowebsite', 'photo')

app/views.py
from django.shortcuts import render
from app.forms import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'app/index.html')

def registration(request):


    if request.user.is_authenticated:
        return render(request, 'app/registration.html')

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = ProfileUserInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'photo' in request.FILES:
                profile.photo = request.FILES['photo']

            profile.save()
        else:
                        # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = ProfileUserInfoForm()

    return render(request, 'app/registration.html', {'user_form': user_form, 'profile_form': profile_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("You are not logged in!")

        else:
            print("login failed!")
            return render(request, 'app/login.html')

    else:
        return render(request, 'app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in!")

templates/app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:registration' %}">Registration</a>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:logout' %}">Logout</a>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:user_login' %}">Login</a>
          </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

  {% block body_block %}
  <h1>hello from basic</h1>
  {% endblock %}
</body>

</html>

templates/app/index.html
<!DOCTYPE html>
{% extends 'app/base.html' %}

{% block body_block %}

{% endblock %}

templates/app/login.html
<!DOCTYPE html>
{% extends 'app/base.html' %}

{% block body_block %}


<div class="container">
  <h1>Login Page</h1>
  <form action="{% url 'app:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">username</label>
    <input type="text" name="username" value="" placeholder="Enter username">

    <label for="password">Password</label>
    <input type="password" name="password" value="" placeholder="Enter password">

    <input type="submit" name="submit" value="Login">
  </form>
</div>
{% endblock %}

templates/app/registration.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
{% load static %}

{% block body_block %}


<div class="container">

  <h1>Registration Page</h1>

  {% if user.is_authenticated %}

  <h1>Thank you for registration</h1>

  {% else %}

  <form enctype="multipart/form-data" method="POST">

  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}

  <input type="submit" name="submit" value="submit">
  </form>

</div>
{% endif %}

{% endblock %}